version: "3.0"

services:
  uecinformal:
    container_name: "uecinformal_back"
    volumes:
      - ./app:/app
      - ./requirements.txt:/app/requirements.txt
    build: .
    ports:
      - 9000:9000


  db:
    container_name: uecinformal_db
    image: postgres:15.2
    ports: 
      - 5432:5432
    volumes:
      - ./sql:/sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
